### ISSUE TITLE
error: XDG_RUNTIME_DIR not set in the environment.

### ISSUE THREAD

**Issue by iewoahz1991** [JackeyLea/Wayland_Freshman#2]
请问下在wl_display_connect时，总返回0，提示error: XDG_RUNTIME_DIR not set in the environment.需要怎么解决啊，感谢

**Comment by tsl115** [comment]
请求下后续的教程还有吗

**Comment by JackeyLea** [comment]
> 请求下后续的教程还有吗

最近半年一直在出差暂时没空研究后续
